postMerge :
  preRun: 
    command:
      - npm install
      
  
  subModules:          #Not to be changed
      
        
      - name:  framesync
        path : "./packages/framesync"
        pattern: 
          - "./packages/framesync/src/_tests/*.ts"
        
        framework : jest
        preRun:
          command:
            - npm i
            - npm run build
          
        postRun:
            command:
              - node --version 
        
      
        
preMerge : 
  
  subModules:          #Not to be changed
     
    - name:  framesync
      path : "./packages/framesync"
      pattern: 
        - "./packages/framesync/src/_tests/*.ts"

      framework : jest
      preRun:
        command:
          - npm i
          - npm run build

      postRun:
          command:
            - node --version
            
parallelism: 2 # this will be depricated in future
version : 2.0
